### ISSUE TITLE
Use proper html & sign

### ISSUE THREAD

**Issue by sangjunp4rk** [mariolozano/prj-rev-bwfs-dasmoto#1]
Use the html & sign instead of just &, which is `&amp;` Continue doing this in the future for all special symbols. You can find all of them here https://www.ascii.cl/htmlcodes.htm

https://github.com/mariolozano/prj-rev-bwfs-dasmoto/blob/master/dasmoto/index.html#L4

**Comment by mariolozano** [comment]
Thx for sharing this resource with me. 
I will use &amp; going forward :-)
